name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: app

      # Configurar ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Especifique a versão do Python que você está usando

      # Instalar dependências do aplicativo
      - name: Install dependencies app
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt  

      # Instalar dependências dos testes
      - name: Install dependencies tests
        run: |
          python -m pip install --upgrade pip
          pip install -r app/tests/requirements.txt  
          
      # Execute os testes
      - name: Run tests
        run: |
          python -m unittest discover -s app/tests

      # Execute a análise do SonarQube
      - name: SonarQubeAnalysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://serveo.net:9000"
