name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Configurar ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Especifique a versão do Python que você está usando

      # Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Substitua requirements.txt pelo nome do seu arquivo de requisitos

      # Execute os testes
      - name: Run tests
        run: |
          python -m unittest discover -s tests

      # Execute a análise do SonarQube
      - name: SonarQubeAnalysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://serveo.net:9000"
